version: "3"

services:
  r:
    image: rocker/verse
    restart: always
    ports:
      # Host runs Rstudio Serrver on 8787
      - "8788:8787"
    env_file: 
      # Template is secret_.env
      - secret.env
    environment:
      - USER=rstudio
      - ROOT=true
    volumes:
      - ~/Documents/R:/home/rstudio/R
