version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  r:
    # image: atusy/atusyverse
    build: "."
    restart: always
    env_file: 
      # Template is secret_.env
      - secret.env
    environment:
      - USER=rstudio
      - ROOT=true
      - VIRTUAL_HOST=rstudio.localhost
    volumes:
      # ln -s ~/Documents/R/ R
      - ./R:/home/rstudio/R
      - /home/atusy:/home/atusy
